name: "📚 Nueva Pregunta"
description: "Agrega una pregunta de admisión UNSA / San Marcos"
title: "[Pregunta] "
labels: ["good first issue", "content"]
body:
    - type: dropdown
    id: topic
    attributes:
      label: "Materia"
      options:
                - Razonamiento Verbal
                - Razonamiento Matemático
                - Historia del Perú
                - Geografía
    validations:
      required: true
    - type: textarea
    id: question
    attributes:
      label: "Pregunta"
      placeholder: "Ej: ¿Sinónimo de CAUTO?"
    validations:
      required: true
    - type: textarea
    id: options
    attributes:
      label: "4 Opciones (separadas por coma)"
      placeholder: "Prudente, Audaz, Ingenuo, Rápido"
    validations:
      required: true
    - type: input
    id: answer
    attributes:
      label: "Respuesta correcta"
      placeholder: "Prudente"
    validations:
      required: true
